channels:
  - conda-forge
  - default
dependencies:
  - python=3.10
  - pip
  - matplotlib
  - numpy
  - scipy
  - scikit-learn
  - libblas[build=*mkl]
  - h5py
  - astropy
  - healpy
  - astropy-healpix
  - pyyaml
  - rich
  - mpi4py
  - mako
  - pycuda
  - line_profiler
  - numba
  - gitpython
  - pip:
    - scikit-cuda
    - hera-calibration
    - matvis
    - fftvis
    - git+https://github.com/HERA-Team/hera_sim.git  # Need for pyuvdata>=2.4.0 compatibility until new release arrives
    - pyuvdata==2.4.5
    - pyradiosky
    - pyuvsim
    - pygdsm
    - uvtools  # TODO: Check if actually using
    - git+https://github.com/zacharymartinot/redshifted_gaussian_fields
