name: h4c
channels:
  - conda-forge
  - default
dependencies:
  - python=3.10
  - pip
  - matplotlib
  - numpy
  - scipy
  - scikit-learn
  - libblas[build=*mkl]
  - h5py
  - astropy
  - healpy
  - astropy-healpix
  - pyyaml
  - rich
  - mpi4py
  - mako
  - pycuda
  - line_profiler
  - pip:
    - scikit-cuda
    - hera-calibration
    - vis-cpu==1.1.0
    - hera_sim==4.1.0
    - pyuvdata==2.3.3
    - pyradiosky==0.3.0
    - git+https://github.com/RadioAstronomySoftwareGroup/pyuvsim.git
    - git+https://github.com/telegraphic/pygdsm.git
    - git+https://github.com/HERA-Team/uvtools.git