name: h4c
channels:
  - conda-forge
  - default
dependencies:
  - python=3.10
  - pip
  - matplotlib
  - numpy
  - scipy
  - scikit-learn
  - libblas[build=*mkl]
  - h5py
  - astropy
  - healpy
  - astropy-healpix
  - pyyaml
  - rich
  - mpi4py
  - mako
  - pycuda
  - line_profiler
  - pip:
    - scikit-cuda
    - hera-calibration
    - vis-cpu==1.1.0
    - git+https://github.com/HERA-Team/hera_sim.git  # Need for pyuvdata>=2.4.0 compatibility until new release arrives
    - pyuvdata==2.4.0
    - pyradiosky==0.3.0
    - pyuvsim=1.2.6
    - pygdsm==1.3.0
    - uvtools==0.2.0  # TODO: Check if actually using